### ISSUE TITLE
Add maintainers file

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/astrolabe#111]
We need a maintainers file that has details on ownership.

In the repositories, there needs to be an MAINTAINERS file that lists all maintainers of the project, and potential stakeholders ([EXAMPLE](https://github.com/goharbor/community/blob/master/MAINTAINERS.md)). (From https://github.com/vmware-tanzu/community-engagement/blob/main/GUIDELINES.md)

**Comment by dsu-igeek** [comment]
Fixed in #115
