### ISSUE TITLE
Failed to find the list of all datastores in VC

### ISSUE THREAD

**Issue by liuhename** [vmware-tanzu/astrolabe#34]
Hi All
I face an issue "Failed to download snapshot, ivd:xxxxxxxxxxxxxxxxxxx, from durable object storage. copyInt failed: ServerFaultCode: InvalidArgument:  is incorrectly formatted", when i restore the backup with command velero restore.

I also look into the pod logs, i find some error log as below. It seems like the pod try to get a datastore list from datacenter.But our policies don't allow this pod get whole datastore list from datacenter.  Can i use any paramters to custom the datastore path for it  ? Could you give me some advice?

time="2020-07-28T14:34:55Z" level=error msg="Failed to find the list of all datastores in VC" error=**"datastore '/xxx-xx01/datastore/*' not found"** logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager_util.go:144"
time="2020-07-28T14:34:55Z" level=error msg="Failed to find any datastore in the underlying vSphere" error=**"datastore '/xxx-xx01/datastore/*' not found"** logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager_util.go:232"
time="2020-07-28T14:34:55Z" level=error msg="Failed to call createCnsVolumeWithClusterConfig" error=**"datastore '/xxx-xx01/datastore/*'** not found" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager_util.go:402"

**Comment by lintongj** [comment]
@liuhename Did you run the restore command in guest cluster?

velero-plugin-for-vsphere have not yet supported for guest cluster. The support will be available in our upcoming release around mid Sept. Please stay tuned.

**Comment by liuhename** [comment]
@lintongj 
What's mean the "guest cluster" ? Could you give me more detail information for it ? Thanks!

**Comment by liuhename** [comment]
I face the new issue as below. I have use the administrator user, but it still said " NoPermission". Please help to have a look
---------------------------------------------------------
2020/11/26 07:58:16 pei = ivd:a8c20914-bf24-448b-b0f6-ab51dda54326:970f8ac4-67bc-4763-a205-2e9d671d2449
time="2020-11-26T07:58:16Z" level=info msg="CreateCnsVolumeInCluster called with args, metadata: {{{} {{{} {{} a8c20914-bf24-448b-b0f6-ab51dda54326} pvc-e4b99c1f-6f27-4e12-9a86-5896f99d2e16 2020-11-24 03:02:57.248 +0000 UTC 0xc000489ba8 0xc000489bfc 0xc000489c1d 0xc000489c2d <nil> []} 1024 [disk] [{{} 5021cb5c-e47d-3dbe-fd18-b3edf947770b}]}} Datastore:datastore-2677 []}" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.2-0.20200901212149-f20520b25c48/pkg/ivd/ivd_protected_entity_type_manager_util.go:404"
time="2020-11-26T07:58:16Z" level=error msg="Failed to create volume. Error: ServerFaultCode: NoPermission" error="ServerFaultCode: NoPermission" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.2-0.20200901212149-f20520b25c48/pkg/ivd/ivd_protected_entity_type_manager_util.go:286"
time="2020-11-26T07:58:16Z" level=error msg="Failed to call createCnsVolumeWithClusterConfig" error="ServerFaultCode: NoPermission" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.2-0.20200901212149-f20520b25c48/pkg/ivd/ivd_protected_entity_type_manager_util.go:416"
time="2020-11-26T07:58:16Z" level=error msg="Failed to copy from remote repository." Remote PEID="ivd:a8c20914-bf24-448b-b0f6-ab51dda54326:970f8ac4-67bc-4763-a205-2e9d671d2449" error="copyInt failed: CreateDisk failed: ServerFaultCode: NoPermission" error.file="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.2-0.20200901212149-f20520b25c48/pkg/ivd/ivd_protected_entity_type_manager.go:335" error.function="github.com/vmware-tanzu/astrolabe/pkg/ivd.(*IVDProtectedEntityTypeManager).copyInt" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:118"
time="2020-11-26T07:58:16Z" level=info msg="Filtering out the retry download request which comes in before next retry time" controller=download generation=3 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:105" name=download-970f8ac4-67bc-4763-a205-2e9d671d2449-21711cce-3a2d-4e03-939f-ef3ef3c50efb namespace=velero phase=Retry

**Comment by lintongj** [comment]
Hi @liuhename,

Would you please share versions of VC & ESX?

Looks like you are using velero-plugin-for-vsphere that consumes astrolabe. Would you please also share versions of velero & velero-plugin-for-vsphere?

velero-plugin-for-vsphere uses vSphere credentail in vSphere CSI driver. Please double check the vSphere user specified in the credential does have Administrator role and make sure it is propagated to children. Also, please refer to https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/100 and see if it helps in your case.

>What's mean the "guest cluster" ? Could you give me more detail information for it ? Thanks!
Guest cluster means Tanzu Kubernetes Grid cluster, which is released along with vSphere 7.0. Please refer to https://blogs.vmware.com/vsphere/2020/03/vsphere-7-tanzu-kubernetes-clusters.html for more detail.

**Comment by lintongj** [comment]
Close it as no follow up questions for a while. Feel free to reopen there is any other related questions.
