### ISSUE TITLE
Unable to specify target datastore for restore

### ISSUE THREAD

**Issue by danielkucera** [vmware-tanzu/astrolabe#43]
First of all, we have a cluster without vSAN.
StorageClass is configured with single static datastore:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-vanilla-block-sc
  selfLink: /apis/storage.k8s.io/v1/storageclasses/example-vanilla-block-sc
  uid: e00d5987-c67b-46b1-b6ce-c73dcd28b4c8
  resourceVersion: '11659564'
  creationTimestamp: '2020-08-11T12:29:14Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.vsphere.vmware.com
parameters:
  DatastoreURL: 'ds:///vmfs/volumes/0c06e8ae-9ff93b29/'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
Backup works okay, I can see the volume in S3 bucket.
The restore procedure is failing for me with error:
```
time="2020-08-12T11:53:59Z" level=info msg="CreateCnsVolumeInCluster called with args, metadata: {{{} {{{} {{} 8c8893f8-fbc8-464c-ac24-7633b3ab8260} pvc-29775058-741d-4617-9a3e-ce18cc5bdead 2020-08-12 11:18:38.569 +0000 UTC 0xc000b78818 0xc000b7884c 0xc000b7885d 0xc000b7886d <nil> []} 300 [disk] [{{} 73e7ad42-ea37-4af8-94f6-90ccc0e1ae56}]}} Datastore:datastore-29 []}" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager_util.go:390"
time="2020-08-12T11:54:10Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=21 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:111" name=upload-fa118876-cefe-44ba-9239-57fa56077826 namespace=velero phase=UploadError
time="2020-08-12T11:54:10Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-fa118876-cefe-44ba-9239-57fa56077826" controller=upload currentTime="2020-08-12 11:54:10.26083292 +0000 UTC m=+2658.530258347" generation=21 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-fa118876-cefe-44ba-9239-57fa56077826 namespace=velero nextRetryTime="2020-08-12 12:08:03 +0000 UTC" phase=UploadError
time="2020-08-12T11:54:10Z" level=info msg="Filtering out the retry download request which comes in before next retry time" controller=download generation=14 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:105" name=download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681 namespace=velero phase=InProgress
time="2020-08-12T11:54:10Z" level=info msg="Ignore retry download request which comes in before next retry time, download CR: download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681" controller=download currentTime="2020-08-12 11:54:10.549658851 +0000 UTC m=+2658.819084243" generation=14 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:111" name=download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681 namespace=velero nextRetryTime="2020-08-12 11:58:59 +0000 UTC" phase=InProgress
time="2020-08-12T11:54:40Z" level=info msg="Filtering out the retry upload request which comes in before next retry time" controller=upload generation=21 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:111" name=upload-fa118876-cefe-44ba-9239-57fa56077826 namespace=velero phase=UploadError
time="2020-08-12T11:54:40Z" level=info msg="Ignore retry upload request which comes in before next retry time, upload CR: upload-fa118876-cefe-44ba-9239-57fa56077826" controller=upload currentTime="2020-08-12 11:54:40.260874529 +0000 UTC m=+2688.530299916" generation=21 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/upload_controller.go:117" name=upload-fa118876-cefe-44ba-9239-57fa56077826 namespace=velero nextRetryTime="2020-08-12 12:08:03 +0000 UTC" phase=UploadError
time="2020-08-12T11:54:40Z" level=info msg="Filtering out the retry download request which comes in before next retry time" controller=download generation=14 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:105" name=download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681 namespace=velero phase=InProgress
time="2020-08-12T11:54:40Z" level=info msg="Ignore retry download request which comes in before next retry time, download CR: download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681" controller=download currentTime="2020-08-12 11:54:40.549796808 +0000 UTC m=+2688.819222199" generation=14 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:111" name=download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681 namespace=velero nextRetryTime="2020-08-12 11:58:59 +0000 UTC" phase=InProgress
time="2020-08-12T11:55:00Z" level=info msg="CNS volume, 4c4d7872-6740-4837-84fa-8e8254934dbf, created" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager_util.go:297"
time="2020-08-12T11:55:00Z" level=error msg="Failed to copy data from data source to newly-provisioned IVD protected entity" logSource="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager.go:340"
time="2020-08-12T11:55:00Z" level=error msg="Failed to copy from remote repository." Remote PEID="ivd:8c8893f8-fbc8-464c-ac24-7633b3ab8260:ea989262-9017-4c97-aa83-773dc1530ca7" error="copyInt failed: ServerFaultCode: NotFound" error.file="/go/pkg/mod/github.com/vmware-tanzu/astrolabe@v0.1.1-0.20200519042640-570f84703079/pkg/ivd/ivd_protected_entity_type_manager.go:217" error.function="github.com/vmware-tanzu/astrolabe/pkg/ivd.(*IVDProtectedEntityTypeManager).Copy" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/dataMover/data_mover.go:118"
time="2020-08-12T11:55:00Z" level=info msg="Download status updated from InProgress to Retry" controller=download generation=14 logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/controller/download_controller.go:348" name=download-ea989262-9017-4c97-aa83-773dc1530ca7-556eeab7-0184-4dd9-9669-b390b74f7681 namespace=velero phase=InProgress
```

I think that the problem lies in creating the Volume. The datamanager tries to create a volume on top of two datastores but this fails because we are not using vSAN, see this intercepted request:
```
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Header xmlns="http://schemas.xmlsoap.org/soap/envelope/"><vcSessionCookie>349b5f29187321d6074726c28294ee865d972333</vcSessionCookie></Header><Body><CnsCreateVolume xmlns="urn:vsan"><_this type="CnsVolumeManager">cns-volume-manager</_this><createSpecs><name>pvc-29775058-741d-4617-9a3e-ce18cc5bdead</name><volumeType>BLOCK</volumeType><datastores type="Datastore">datastore-29</datastores><datastores type="Datastore">datastore-30</datastores><metadata><containerCluster><clusterType>KUBERNETES</clusterType><clusterId>***</clusterId><vSphereUser>os-kucera-test@vsphere.local</vSphereUser></containerCluster><entityMetadata xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="CnsKubernetesEntityMetadata"><entityName>pvc-29775058-741d-4617-9a3e-ce18cc5bdead</entityName><entityType>PERSISTENT_VOLUME</entityType></entityMetadata></metadata><backingObjectDetails xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="CnsBlockBackingDetails"><capacityInMb>300</capacityInMb></backingObjectDetails></createSpecs></CnsCreateVolume></Body></Envelope>
```
This is the code responsible for the creation:
https://github.com/vmware-tanzu/astrolabe/blob/cbccec55866ecb5b69ba1a8d947b45d153b8e1f3/pkg/ivd/ivd_protected_entity_type_manager_util.go#L230

https://github.com/vmware-tanzu/astrolabe/blob/cbccec55866ecb5b69ba1a8d947b45d153b8e1f3/pkg/ivd/ivd_protected_entity_type_manager_util.go#L250

**Comment by danielkucera** [comment]
vSphere CSI in contrast is creating the volume like this:
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/f3c03a6a61aeeb72aaf90177024d0fa746f74ee3/pkg/csi/service/common/vsphereutil.go#L199

first it checks if datastore is statically defined in SC and only in case it is not, it tries to create volume on top of all datastores visible to all cluster nodes

**Comment by danielkucera** [comment]
I have found out that one of our datastores is "locked" (creation of volume returns success but in fact it isn't created) 

Would it be possible to specify which datastore to use?

**Comment by lintongj** [comment]
> I have found out that one of our datastores is "locked" (creation of volume returns success but in fact it isn't created)
> 
> Would it be possible to specify which datastore to use?

No. 

What is access mode for this "locked" datastore? Does it happen to be the most spacious datastore?

Would it be possible for you to try to restore after unmounting the "locked" datastore via VCenter?

**Comment by danielkucera** [comment]
I have opened a ticket with vmware support SR 20148919208 to "unlock" the datastore without an answer so far.

**Comment by danielkucera** [comment]
> > Would it be possible to specify which datastore to use?
> 
> No.
> 
This is a wrong design then IMHO. How can you choose a "random" datastore? It would be logical to use the one where the original volume was residing.

**Comment by danielkucera** [comment]
This is also in conflict with topology aware volume provisioning:
https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/deploying_csi_with_zones.html

**Comment by lintongj** [comment]
> > > Would it be possible to specify which datastore to use?
> > 
> > 
> > No.
> 
> This is a wrong design then IMHO. How can you choose a "random" datastore? It would be logical to use the one where the original volume was residing.
@danielkucera 

Actually, there is no interface for user to specify which datastore to restore to. Users use Velero CLI to handle backup&restore. Velero doesn't support to specify target datastore in the restore command. So, velero-plugin-for-vsphere v1.0.1 handles the PV placement itself and always select the most spacious datastore which has access to all worker nodes(VM). 

Ideally, we should consider StorageClass in the backup as well while handling the PV placement as mentioned in https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/master/FAQ.md#v101. In the upcoming release, we will be using dynamic provisioning in the restore path, which would be aligned with vSphere CSI.

**Comment by danielkucera** [comment]
I think it would be best to add an annotation to PV specifying used datastore during backup and when doing restore, read this annotation and restore to the same datastore.

**Comment by lintongj** [comment]
> I think it would be best to add an annotation to PV specifying used datastore during backup and when doing restore, read this annotation and restore to the same datastore.

@danielkucera 

Would you please share the reason why do you require to restore to the same datastore? And this proposed method doesn't works well if the same datastore is down or has no enough space in the original cluster while doing the restore, or if it is a restore to a new cluster (in the cluster migration case). 

Generally, it should be fine if a PV is restored to a datastore with compatible storage policy with the original datastore. And this feature will come along with the next release.

**Comment by danielkucera** [comment]
In our case for example, we have two SANs in two datacenters cross-replicated to the other datacenter. Cluster can see datastores (LUNs) from from both SANs (thanks to spanned SAN network) but it is suboptimal to use datastore from other DC because of latency and wasting bandwith. That's why we want to have precise control about the used datastore.

We are able to do this with StorageClass as this allows specifying the target datastore but in case of recovery with velero we would be out of control.

It should be at least possible to try with the original datastore and in case of failure retry with your original "best fit" approach.

**Comment by lintongj** [comment]
The `Changing PV/PVC Storage Classes` section in https://velero.io/docs/v1.4/restore-reference/ might help you with specifying expected target datastore for the restore. Along with our next release, the issue should be fixed properly.

**Comment by danielkucera** [comment]
Can you please explain how to use this? How can it help? I am not getting your point.

**Comment by danielkucera** [comment]
after hardcoding the datastore name like following and recompiling, I was able to restore the PV:
```
                if ds.Name() == "datastore-a" {
                        dsList = append(dsList, ds.Reference())
                        logger.Infof("datastore, %v, added", ds.Reference())
                        continue
                }
```

**Comment by lintongj** [comment]
> The `Changing PV/PVC Storage Classes` section in https://velero.io/docs/v1.4/restore-reference/ might help you with specifying expected target datastore for the restore. Along with our next release, the issue should be fixed properly.

Velero starts to support the StorageClass mapping in the restore case from v1.4. Before running velero restore, users are supposed to create a StorageClass with target datastore being specified (vSphere specific) and to create a ConfigMap with StorageClass mapping from the one in backup to the one newly created. In this way, it will ensure volumes are restored into the target datastore as users expect. The feature will work well with velero-plugin-for-vsphere in the next release.

**Comment by danielkucera** [comment]
That sounds good. What about the case when the original SC is the SC I'd like to use for creating restore PV? Do I still need to do the mapping or will it automatically respect the datastore?

**Comment by lintongj** [comment]
Then you don't have to explicitly create the configmap with the mapping if the storageclass stay the same. But you have to make sure the SC is available in the target cluster.

**Comment by danielkucera** [comment]
Perfect. Is there a timeline for this to be implemented?

**Comment by lintongj** [comment]
Late September/early October. Will update in this thread if there is any change of plan.

**Comment by danielkucera** [comment]
Hi @lintongj , do you have any updates regarding this?

**Comment by lintongj** [comment]
Hi @danielkucera, 

Our release gets postponed around a month. This task is in our TODO list.

**Comment by lintongj** [comment]
@danielkucera 
FYI, the updated release date (of velero-plugin-for-vsphere) will be around early December.

**Comment by lintongj** [comment]
Close as velero-plugin-for-vsphere 1.1.0 was released last December.
